### ISSUE TITLE
When image uploads Internal page link show text box with value 0 instead of the page heirarchy

### ISSUE THREAD

**Issue by mirzadabeer** [justb3a/processwire-fieldtypeimageextra#1]
As I am new to processwire, I have recently installed your module for one of my project, Facing the below issue.

* Intially when i upload an image the internal links shows a textbox with value 0 rather than to ask the internal page selection heirarchy as shown in the below screenshot.
<img width="1230" alt="screen shot 2017-03-22 at 6 06 09 pm" src="https://cloud.githubusercontent.com/assets/22817400/24201758/7408f098-0f2a-11e7-82ef-c670825965ee.png">

* Once the page is saved then it is showing the page heirarchy as show in the below screenshot.
<img width="1167" alt="screen shot 2017-03-22 at 6 05 49 pm" src="https://cloud.githubusercontent.com/assets/22817400/24201759/742b8cd4-0f2a-11e7-8faa-ec646ef4f8d9.png">

do you have any inputs or thoughts or suggestions to it?

**Comment by justb3a** [comment]
hi, I guess that the JavaScript file which creates the pagetree to choose from is missing initially.
Which version of ProcessWire do you use and are you using the latest module version?

The module checks whether the link field is enabled, and if so, it adds the necessary js file (line 112):

```php
if (isset($this->additionalFields['link'])) {
            $this->config->scripts->append($this->config->urls->InputfieldPageListSelect . 'InputfieldPageListSelect.min.js');
          }
```

**Comment by mirzadabeer** [comment]
Hi, Thanks for the quick reply.

ImageExtra : 1.0.4
processwire : 3.0

InputfieldPageListSelect.min.js already loaded, but still its not creating the page tree, Please find the below screenshot for the same.

<img width="1435" alt="screen shot 2017-03-22 at 6 48 35 pm" src="https://cloud.githubusercontent.com/assets/22817400/24203924/72438466-0f30-11e7-913e-d4aba5b58188.png">

after debugging found that, $field->attr('value', (int)$pagefile->link); line No: 1332, $pagefile->link is returning null.

![screen shot 2017-03-22 at 6 53 10 pm](https://cloud.githubusercontent.com/assets/22817400/24204158/193cab58-0f31-11e7-9fc2-3f114a4b01a0.png)

**Comment by justb3a** [comment]
wow. I didn't notice that your are using this old module.

> This module is obsolete and will not be developed any further. Please use the [ImageExtra module](https://github.com/justb3a/processwire-imageextra) instead.
